import Head from 'next/head'
import { Livvic } from 'next/font/google'

const livvic = Livvic({ 
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={livvic.className}>
      <h1>Home Page</h1>

      {/* Socials */}

      {/* Banner */}

      {/* NavBar */}

      {/* Hero */}

      </main>
    </>
  )
}
